### PR TITLE
Optimize: optimize memory copy in MemoryBlock by move constructor and move assignment.

### PR DESCRIPTION
**Pull request by ifplusor**
optimize memory copy in MemoryBlock by move constructor and move assignment.

### CODE REVIEW

**Comment by jovany-wang** [comment]
No need to change such many codes that looks like nothing different.

**Comment by ifplusor** [comment]
> No need to change such many codes that looks like nothing different.

CRLF -> LF

**Comment by jovany-wang** [comment]
@ifplusor  Thanks for your explanations.
I don't  think we should to change `CRLF` to `LF` in a feature change  PR.
It will make us confused for your changes.

I think it's better to request another PR to do the `CRLF` change.
In this PR, just to do the Optimization, so that we could read what you changed.

**Comment by ifplusor** [comment]
> @ifplusor Thanks for your explanations.
> I don't think we should to change `CRLF` to `LF` in a feature change PR.
> It will make us confused for your changes.
> 
@jovany-wang yeah, i will split commit.

**Pull request merged**
