### PR TITLE
replace boost log with spdlog

### PR DESCRIPTION
**Pull request by apppur**
## What is the purpose of the change

replace boost log with spdlog

## Brief changelog

replace boost log with spdlog

## Verifying this change

replace boost log with spdlog

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when a cross-module dependency exists.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by jovany-wang** [comment]
Can you resolve the conflicts?

**Comment by apppur** [comment]
> Can you resolve the conflicts?

done

**Comment by ifplusor** [comment]
@apppur I think change all LOG statements is bad, so I do some changes base on your PR. Please check https://github.com/ifplusor/rocketmq-client-cpp/commit/f83ed51eeb9f9d12ff3ba953d39a19bf48717143

**Comment by apppur** [comment]
> @apppur I think change all LOG statements is bad, so I do some changes base on your PR. Please check [ifplusor@f83ed51](https://github.com/ifplusor/rocketmq-client-cpp/commit/f83ed51eeb9f9d12ff3ba953d39a19bf48717143)
No problem, this modification makes the code very elegant. Thanks

**Comment by apppur** [comment]
> @apppur I think change all LOG statements is bad, so I do some changes base on your PR. Please check [ifplusor@f83ed51](https://github.com/ifplusor/rocketmq-client-cpp/commit/f83ed51eeb9f9d12ff3ba953d39a19bf48717143)
No problem, this modification makes the code very elegant. Thanks! Now do I have to make changes from your branch and resubmit PR?

**Comment by ifplusor** [comment]
@apppur You can do this job on you own branch, and do force push to overwrite commits log on this PR. My code is only a suggestion, and do it as you think.

**Comment by apppur** [comment]
> @apppur You can do this job on you own branch, and do force push to overwrite commits log on this PR. My code is only a suggestion, and do it as you think.

OK, I will do it as your suggestion

**Pull request closed without merging**
