### PR TITLE
Reconstructed Apache RocketMQ cpp client

### PR DESCRIPTION
**Pull request by ifplusor**
## What is the purpose of the change

Reconstruct Apache RocketMQ cpp client for new major version.

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when a cross-module dependency exists.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by vongosling** [comment]
Do we have any plan to merge the similar improvement in the community?

**Comment by vongosling** [comment]
Do we have any plan to merge the similar improvement in the community?

**Comment by ifplusor** [comment]
@vongosling 因为要考虑SDK的异步特性，cpp层的接口设计还需要配合对象的生命周期管理做出调整（同时兼顾C接口适配的简便），从而保证临界条件下也不会引起非法地址访问，暂时还没有合并计划。如果openmessaging的cpp接口稳定，也可能直接兼容到最新的规范。

**Comment by ShannonDing** [comment]
@ifplusor Could you plz fix the conflicts? I will merge this PR re_dev branch first and do refactors later.

**Comment by ifplusor** [comment]
@ShannonDing 冲突解决不了的，两边不兼容，是不同的演进方向。

**Pull request merged**
