### PR TITLE
Fixed TpsReportService::start

### PR DESCRIPTION
**Pull request by ifplusor**
## What is the purpose of the change

Fixed TpsReportService::start().

## Brief changelog

Create thread if tps_thread_ is nullptr.

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when a cross-module dependency exists.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by phaniranjan** [comment]
Thank you Shannon for the quick fix. This issue was causing all producer/consumer examples to fail at the same location. I will try to execute the current fix.

**Comment by phaniranjan** [comment]
I have rebuilt the sources with this fix & tried to execute, the thread starts without issue but there is another exception message shown in the logs & consumer will lead to a segmentation fault. Let me know if the usage parameters are not missing or require additional input values.

[vectone@localhost example]$ !714
./AsyncProducer -n "localhost:9876" -g "TestGroup" -t "MyTopicMessage"
nameserver: localhost:9876
topic: MyTopicMessage
groupname: TestGroup
produce content: msgbody for test
msg  count: 1
thread count: 8
send Exception
send Exception
send Exception
send Exception
send Exception
send Exception
send Exception
send Exception
send Exception
per msg time: 6ms
========================finished==============================
tps: 26
[vectone@localhost example]$ !715
./AsyncPushConsumer -n "localhost:9876" -g "TestGroup" -t "MyTopicMessage"
nameserver: localhost:9876
topic: MyTopicMessage
groupname: TestGroup
produce content: msgbody for test
msg  count: 1
thread count: 8
Segmentation fault (core dumped)
[vectone@localhost example]$

**Comment by ifplusor** [comment]
@phaniranjan I have no idea for this, could you post stacktrack?

**Review by ShannonDing — APPROVED** [review]

**Comment by phaniranjan** [comment]
@ifplusor Hello James, Issue occurs when the thread count is more than 1 and AsycPushConsumer gives segmentation fault. But i was able to verify with single thread producer & Pull consumer. Message exchanges happen

[root@localhost example]# !237
./PullConsumer -n "localhost:9876" -g "TestGroup" -t "MyTopicMessage" -T "1"
nameserver: localhost:9876
topic: MyTopicMessage
groupname: TestGroup
produce content: msgbody for test
msg  count: 1
thread count: 1
mq:MessageQueue [topic=MyTopicMessage, brokerName=localhost.localdomain, queueId=0]
mq:MessageQueue [topic=MyTopicMessage, brokerName=localhost.localdomain, queueId=1]
mq:MessageQueue [topic=MyTopicMessage, brokerName=localhost.localdomain, queueId=2]
mq:MessageQueue [topic=MyTopicMessage, brokerName=localhost.localdomain, queueId=3]
32
PullResult [ pullStatus=FOUND, nextBeginOffset=32, minOffset=0, maxOffset=473, msgFoundList=32 ]
PullResult [ pullStatus=FOUND, nextBeginOffset=32, minOffset=0, maxOffset=473, msgFoundList=32 ]
=======================================================
MessageExt [queueId=0, storeSize=180, queueOffset=0, sysFlag=0, bornTimestamp=1590176905475, bornHost=10.22.7.89, storeTimestamp=1590176905519, storeHost=10.22.7.89, msgId=7F00000121D6439F85AE706595030000, commitLogOffset=899630, bodyCRC=1797452670, reconsumeTimes=0, preparedTransactionOffset=0,  Message [topic=MyTopicMessage, flag=0, tag=*]]
=======================================================.

**Pull request merged**
