### PR TITLE
[Test][Don't Merge] Fix CI

### PR DESCRIPTION
**Pull request by jovany-wang**
Test if CI is available after fixing.

### CODE REVIEW

**Comment by messense** [comment]
The issue is not with bash path, you need to fix this:

```
error: Name clash for '<p/home/travis/build/apache/rocketmq-client-cpp/bin/lib>libboost_system.a'
error: 
error: Tried to build the target twice, with property sets having 
error: these incompatible properties:
error: 
error:     -  <runtime-link>static <warnings>all
error:     -  <runtime-link>shared <warnings>on
error: 
error: Please make sure to have consistent requirements for these 
error: properties everywhere in your project, especially for install
error: targets.
```

**Comment by messense** [comment]
Also, this is very likely to hit Travis CI log length limit: https://docs.travis-ci.com/user/common-build-problems/#log-length-exceeded

You might want to find a way to workaround that, you can take inspiration from https://github.com/messense/rocketmq-python/blob/162a8a4e3b35fa489948aacc130832a51a34c280/.travis.yml#L35-L36

**Comment by jovany-wang** [comment]
@messense Thanks for pointing out this.

**Comment by stcai** [comment]
If done use 'runtime-link=static' while building boost, we  can walk around this error. 
But I don't know why.
If we don't really want to link C++ runtime library to libmqclient.so statically, this option can be remove from the build script.

**Comment by ShannonDing** [comment]
The issue #56 is fixed by PR #62, this PR will be closed asap.

**Pull request closed without merging**
