### PR TITLE
fix SendMessageRequestHeader Serialization bug

### PR DESCRIPTION
**Pull request by shenhui0509**
## What is the purpose of the change

Fix Bug for Send batch messages

## Brief changelog

let bool fields in request header be serialized into bool rather than string "1" or "0"; 

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when a cross-module dependency exists.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by shenhui0509** [comment]
the send message request header is serialized to 
```
{"code":10,"extFields":{"batch":"1","unitMode":"false"},"flag":0,"language":"JAVA","opaque":0,"serializeTypeCurrentRPC":"JSON","version":0}
```
however in broker the boolean field is deserialized as false, so treat the send batch request as a single message, results in bug.

**Comment by shenhui0509** [comment]
ping @ifplusor @ShannonDing

**Comment by ifplusor** [comment]
I think you can add a specialization of ```UtilAll::to_string``` such as:

```c++
template <>
inline std::string UtilAll::to_string<bool>(bool value) {
  return value ? "true" : "false";
}
```

see: https://github.com/ifplusor/rocketmq-client-cpp/blob/a750efad307a98c49b20d2beebc763633af2e472/src/common/UtilAll.h#L153

**Comment by shenhui0509** [comment]
> The extFields is map<string, string>, so I think you should add a specialization of `UtilAll::to_string`. For example:
> 
> ```c++
> template <>
> inline std::string UtilAll::to_string<bool>(bool value) {
>   return value ? "true" : "false";
> }
> ```
> 
> see: https://github.com/ifplusor/rocketmq-client-cpp/blob/a750efad307a98c49b20d2beebc763633af2e472/src/common/UtilAll.h#L153

resolved

**Pull request merged**
