### PR TITLE
Upgrade libevent version to 2.1.8

### PR DESCRIPTION
**Pull request by tinycedar**
On my latest macOS(10.14.1), a warning message occurs:
 ```[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0```
according to [issue from libevent](https://github.com/libevent/libevent/issues/376), it was fixed as of version 2.1.8. So I send this pull request.

### CODE REVIEW

**Comment by jovan-wong** [comment]
Looks good!

**Comment by ShannonDing** [comment]
Upgrading the version of the dependent package is a very big change and needs to be verified, including the regression of existing functions and testing on other platforms, such as centos, windows, etc.

**Comment by ifplusor** [comment]
Upgrade libevent to 2.1.11-stable is better.

**Comment by ShannonDing** [comment]
link #211, it is better to update 1.1.11 directly.

**Comment by ShannonDing** [comment]
link #228

**Pull request closed without merging**
